version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - examples

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

linters-settings:
  govet:
    check-shadowing: true
